language: c
sudo: required
install:
  - pip install --user cpp-coveralls
before_script:
  - git clone https://github.com/mkschreder/libutype.git libutype
  - pushd libutype && autoreconf -if && ./configure --prefix=/usr/ && make && sudo make install && popd
script: autoreconf -if && ./configure --enable-code-coverage && make && make check
after_success:
  - coveralls
addons:
  apt:
    packages:
    - lcov
